export const ADD_USER = 'ADD_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';


export const CHANGE_VIEW = 'CHANGE_VIEW';


export const RECEIVE_ALERTS = 'RECEIVE_ALERTS';
export const UPDATE_CURRENT_ALERTS = 'UPDATE_CURRENT_ALERTS';
export const ADD_ALERT = 'ADD_ALERT';

export const RECEIVE_INTERESTS = 'RECEIVE_INTERESTS';





